Update
- Add get_applications and check_applications functions
- Improve output formatting

diff --git a/signature_check b/signature_check
--- a/signature_check
+++ b/signature_check
@@ -34,6 +34,39 @@ function ctrl_c {
 }
 
 
+function get_applications {
+
+  while IFS=$'\n' read -r app; do 
+    apps+=("${app}"); 
+  done < <(system_profiler SPApplicationsDataType \
+            | grep "Location: " \
+            | awk -F ': ' '{print $2}')
+}
+
+
+function check_applications {
+
+  for app in "${apps[@]}"; do
+    if ! pkgutil --check-signature "${app}" >/dev/null; then
+      
+      output="$(pkgutil --check-signature "${app}")"
+      if echo "${output}" | grep -q "no signature"; then
+        not_signed+=("${app}");
+
+      elif echo "${output}" | grep -q "untrusted certificate"; then
+        signed_with_untrusted_certificate+=("${app}");
+
+      elif echo "${output}" | grep -q "invalid"; then
+        broken_signature+=("${app}");
+      fi
+    
+    elif spctl --assess -v "${app}" 2>&1 | grep -q 'Notarized' ; then
+      notarized+=("${app}");
+    fi
+done
+}
+
+
 function main {
 
   trap ctrl_c SIGINT
@@ -41,31 +74,12 @@ function main {
 
   declare -a apps
   declare -a notarized
-  declare -a no_signature
-  declare -a untrusted_certificate
-  declare -a broken
+  declare -a not_signed
+  declare -a signed_with_untrusted_certificate
+  declare -a broken_signature
 
-  while IFS=$'\n' read -r app; do 
-    apps+=("${app}"); 
-  done < <(system_profiler SPApplicationsDataType \
-            | grep "Location: " \
-            | awk -F ': ' '{print $2}')
-
-
-  for app in "${apps[@]}"; do
-    if ! pkgutil --check-signature "${app}" >/dev/null; then
-      output="$(pkgutil --check-signature "${app}")"
-      if echo "${output}" | grep -q "no signature"; then
-        no_signature+=("${app}");
-      elif echo "${output}" | grep -q "untrusted certificate"; then
-        untrusted_certificate+=("${app}");
-      elif echo "${output}" | grep -q "invalid"; then
-        broken+=("${app}");
-      fi
-    elif spctl --assess -v "${app}" 2>&1 | grep -q 'Notarized' ; then
-      notarized+=("${app}");
-    fi
-  done
+  get_applications
+  check_applications
 
 
   if [ ${#notarized[@]} -gt 0 ]; then
@@ -73,31 +87,31 @@ function main {
     for app in "${notarized[@]}"; do
       echo "  ${app}"
     done
+    echo
   fi
 
-  echo
-  
-  if [ ${#no_signature[@]} -gt 0 ]; then
-     echo "${RED}Not Signed (${#no_signature[@]}):${RESET}" 
-    for app in "${no_signature[@]}"; do
+
+  if [ ${#not_signed[@]} -gt 0 ]; then
+     echo "${RED}Not Signed (${#not_signed[@]}):${RESET}" 
+    for app in "${not_signed[@]}"; do
       echo "  ${app}"
     done
+    echo
   fi
 
-  echo
 
-  if [ ${#untrusted_certificate[@]} -gt 0 ]; then
-    echo "${RED}Signed with untrusted certificate (${#untrusted_certificate[@]}):${RESET}" 
-    for app in "${untrusted_certificate[@]}"; do
+  if [ ${#signed_with_untrusted_certificate[@]} -gt 0 ]; then
+    echo "${RED}Signed with untrusted certificate (${#signed_with_untrusted_certificate[@]}):${RESET}" 
+    for app in "${signed_with_untrusted_certificate[@]}"; do
       echo "  ${app}"
     done
+    echo
   fi
 
-  echo 
 
-  if [ ${#broken[@]} -gt 0 ]; then
-    echo "${RED}Broken Signature: (${#broken[@]}):${RESET}" 
-    for app in "${broken[@]}"; do
+  if [ ${#broken_signature[@]} -gt 0 ]; then
+    echo "${RED}Broken Signature: (${#broken_signature[@]}):${RESET}" 
+    for app in "${broken_signature[@]}"; do
       echo "  ${app}"
     done
   fi
